### PR TITLE
updated the error message

### PR DESCRIPTION
**Pull request by prabhanshu**
#### What does this PR do? Please provide some context
Based on the feedback of Jeff, updating the error message

#### Definition of done:
- [ ] Title of the pull request is clear and informative
- [ ] Add pull request hyperlink to relevant TFS items
- [ ] For large or complex change: schedule an in-person review session
- [ ] This change has appropriate test coverage
- [ ] Get at least two approvals

#### Reminders DURING merge
1. If you're merging from a short-term (feature) branch into a long-term branch (like dev, release, or master) then "Squash and merge" to keep our history clean.
1. If merging from two longterm branches (like cherry picks from upstream, dev to release, etc) then "Create merge commit" to preserve individual commits.

[//]: # ( fyi: This content was heavily inspired by )
[//]: # ( 1 Our team's policies and processes )
[//]: # ( 2 https://github.com/sprintly/sprint.ly-culture/blob/master/pr-template.md )
[//]: # ( 3 The book "The Checklist Manifesto: How to Get Things Right" by Atul Gawande )
[//]: # ( 4 https://github.com/Azure/azure-event-hubs/blob/master/.github/PULL_REQUEST_TEMPLATE.md )

Configuration Pull Request
---
#### (For changes proposed to upstream)
Make sure that the following steps are done before merging

  - [ ] @devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overridden when this goes live?  
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

### CODE REVIEW

**Review by manikarthikk — APPROVED** [review]

**Review by eltoncarr-ms — COMMENTED** [review]
You could also use a variable placeholder that defaults to the existing message and use our configuration override to set this message in place as opposed to hard coding it here. If this is NOT a change we need to port over, it really doesn't matter. If we intend to migrate this, it needs to be done using overrides as opposed to hard coding it.

**Comment by prabhanshu** [comment]
@eltoncarr 
Added the variable placeholder that defaults to the existing message. 
Added the configuration (https://github.com/Microsoft/oxa-tools/pull/387 ) which will override the message

**Comment by prabhanshu** [comment]
@eltoncarr review required?

**Review by eltoncarr-ms — APPROVED** [review]
looks good

**Pull request merged**
